language: ruby
cache: bundler
rvm:
  - 2.1.2
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
bundler_args: --without development:production
before_script:
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:create db:schema:load db:migrate db:seed
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 5 # give xvfb some time to start
env:
  global:
    - BUNDLE_JOBS=4
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
script:
  - bundle exec rspec
